### ISSUE TITLE
Need to bump bootprint dep

### ISSUE THREAD

**Issue by chrisdostert** [gnomeontherun/gitbook-plugin-swagger#2]
Attempting to use the plugin causes the following error:
"Engine 'uglify' not found. Refusing to store configuration"

It appears to potentially be solvable by simply updating to the latest version of the dependency: 
https://github.com/bootprint/bootprint-base/issues/1

**Comment by chrisdostert** [comment]
@gnomeontherun sweet; thx for accepting the PR. Any way you could republish to npm? -Cheers

**Comment by alphon-sh** [comment]
@chrisdostert Thanks, working great with new version of bootprint.

**Comment by gnomeontherun** [comment]
Released v0.1.1! Thanks for the help, I really appreciate it!
