### ISSUE TITLE
Broken link to bundle.js

### ISSUE THREAD

**Issue by timothymcmackin** [gnomeontherun/gitbook-plugin-swagger#5]
The generated HTML pages have a reference to bundle.js:

`<script src="bundle.js" type="application/javascript"></script>`

That JS file isn't found in the built book.

To debug, I've removed all of my other plugins, so this JS link must be coming from this plugin. I'm using gitbook 3.2.3.

**Comment by gnomeontherun** [comment]
There is no place in this plugin that tries to load a file named `bundle.js`, so I'm not sure exactly how this comes to be. Do you have a project somewhere on github that I could see?

**Comment by timothymcmackin** [comment]
Here's a sample gitbook project that I reproduced the issue in:

https://github.com/timothymcmackin/Sample-Gitbook/blob/master/book/_book/swagger-page.html#L2886

Not sure where that bundle.js comes from...

**Comment by gnomeontherun** [comment]
Thanks, it must be getting added by one of the dependencies. Looking into it.

**Comment by gnomeontherun** [comment]
Yup, bootstrap-base added more templates that needed to be overridden. Will push a fix for this shortly.

**Comment by gnomeontherun** [comment]
Should be resolved by 2e5096a3ac368d7565f444de4c92b572a94f801c. Bumped to `v0.1.2`. Let me know

**Comment by timothymcmackin** [comment]
That fixed it for me. Thanks for addressing that!

**Comment by gnomeontherun** [comment]
My pleasure!
